export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  completeProfile: '/complete-profile',
  dashboard: '/dashboard',
  add: '/add',
  calendar: '/calendar',
  more: '/more',
  workspace: '/workspace',
  createWorkspace: '/workspace/create',
  accounts: '/accounts',
  transactions: '/transactions',
  categories: '/categories',
  savings: '/savings',
  budgets: '/budgets',
  activity: '/activity',
  recurring: '/recurring',
  debts: '/debts',
  business: '/business',
  reports: '/reports',
  settings: '/settings',
  currencySettings: '/settings/currency',
  workspaceSettings: '/settings/workspace',
  syncCenter: '/settings/sync',
} as const

export const routeLabels: Record<string, string> = {
  [routes.home]: 'Home',
  [routes.login]: 'Login',
  [routes.register]: 'Register',
  [routes.forgotPassword]: 'Forgot password',
  [routes.completeProfile]: 'Complete profile',
  [routes.dashboard]: 'Home',
  [routes.add]: 'Add',
  [routes.calendar]: 'Calendar',
  [routes.more]: 'More',
  [routes.workspace]: 'Spaces',
  [routes.createWorkspace]: 'Create space',
  [routes.accounts]: 'Accounts',
  [routes.transactions]: 'Transactions',
  [routes.categories]: 'Categories',
  [routes.savings]: 'Savings',
  [routes.budgets]: 'Budgets',
  [routes.activity]: 'Activity',
  [routes.recurring]: 'Recurring',
  [routes.debts]: 'Debts',
  [routes.business]: 'Business',
  [routes.reports]: 'Reports',
  [routes.settings]: 'Settings',
  [routes.currencySettings]: 'Currency settings',
  [routes.workspaceSettings]: 'Space settings',
  [routes.syncCenter]: 'Sync center',
}
